<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>HardlineLeaderboard</AssemblyName>
    <RootNamespace>HardlineLeaderboard</RootNamespace>
    <Nullable>disable</Nullable>
    <LangVersion>9</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Project Hardline\BepInEx\core\BepInEx.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Project Hardline\BepInEx\core\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Project Hardline\Project Hardline_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Project Hardline\Project Hardline_Data\Managed\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Project Hardline\Project Hardline_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Mirror">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Project Hardline\Project Hardline_Data\Managed\Mirror.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.JSONSerializeModule">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Project Hardline\Project Hardline_Data\Managed\UnityEngine.JSONSerializeModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="com.rlabrecque.steamworks.net">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Project Hardline\Project Hardline_Data\Managed\com.rlabrecque.steamworks.net.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
